### ISSUE TITLE
Errors are in the wrong order?

### ISSUE THREAD

**Issue by EMattfolk** [sylt-lang/sylt-lang#625]
```
do_something :: fn l: [int] do end

start :: fn do
    a :: 1
    do_something(a)
end
```

```
typecheck error: tests/hm_typing/testtest.sy:5
      A '[int]' cannot be a 'int'
      Types don't match
   3 | start :: fn do
   4 |     a :: 1
   5 |     do_something(a)
                        ^
```
I would expect the error to be
```
typecheck error: tests/hm_typing/testtest.sy:5
      A 'int' cannot be a '[int]'
      Types don't match
   3 | start :: fn do
   4 |     a :: 1
   5 |     do_something(a)
                        ^
```

**Comment by FredTheDino** [comment]
HM doesn't really care about the order there. This change is surprisingly hard to make and to make it better. Since most relations are symmetrical in the type-system, we check them twice (one in each direction). The given type-constraint can have come from anywhere. There might be a different solution where we give more helpful information.

Maybe we could add where we think (because there can be multiple places) the variable we're matching again is comming from, with a span or what not.

Or we could try to break out the expressions and say what has what type in the expression you're looking it. Maybe an error like:
```
typecheck error: tests/hm_typing/testtest.sy:5
      A '[int]' cannot be a 'int'
      Types don't match
   3 | start :: fn do
   4 |     a :: 1
   5 |     do_something(a)
                        ^
 a : int
 argumentName, someVariable, abc : [int]
```

Or maybe we could add a certinty score to each type, and we add a hint pointing to the expression we're uncertain-about, something like:

```
typecheck error: tests/hm_typing/testtest.sy:5
      A '[int]' cannot be a 'int'
      Types don't match
   3 | start :: fn do
   4 |     a :: 1
   5 |     do_something(a)
                        ^
help:
	It looks like the expression:
		`a`
	should have the type `[int]`, since that is the type of argument #0 of `do_something`
```
?

But I can understand that you're a bit frustrated with the error message.

**Comment by FredTheDino** [comment]
Closing this. I don't think we can fix it.
