### ISSUE TITLE
Post VM sylt

### ISSUE THREAD

**Issue by EMattfolk** [sylt-lang/sylt-lang#628]
- [x] Write std in sylt where possible
 - [x] Maybe type
 - [ ] Better indexing code generation
 - [x] Mapping options?
 - [ ] Iterators
 - [x] Yeet std-common::Value and std-common::Type

I think there are more things we could do. Feel free to edit.

**Comment by FredTheDino** [comment]
What does it mean to `fix indexing` - could you be more specific?

**Comment by EMattfolk** [comment]
> What does it mean to `fix indexing` - could you be more specific?

I guess it is just implementing indexing without using a complicated function. It should be possible by using the type information.

**Comment by FredTheDino** [comment]
That's gonna be pretty big - we're gonna have to be doing compile-time optimizations. And it's not as easy as "just inline the function", since we in some places don't know what type something is. Consider this code:
```
f :: fn a -> a[0] end

start :: fn do
	f' (1, 2)
	f' { 0 : 1, 1 : 2 }
end
```
We'd need to realize we need two functions in compile-time here, and generate those functions.

TBH - I'm leaning a bit towards wrapping the indexing in functions, since we probably want to return maybe if it cannot find it. But I might be over thinking.

But I feel like that point is hiding a lot of complexity.

**Comment by FredTheDino** [comment]
Gonna close this since it looks like we've fazed out this whole ordeal.
